name: Daily Job Scrape

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (4x daily)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        working-directory: ./collector
        run: pip install -r requirements.txt
        
      - name: Run scraper
        working-directory: ./collector
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python collector.py
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scraper-logs
          path: ./collector/*.log
