name: Daily Job Scrape

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (4x daily)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: node scraper.js
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scraper-logs
          path: scraper.log
