name: Embed Jobs

on:
  schedule:
    - cron: '0 12 * * *' # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        working-directory: ./collector
        run: pip install -r requirements.txt
        
      - name: Run embedding
        working-directory: ./collector
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python embed_jobs.py
